# Generated by Django 5.1.5 on 2025-10-03 14:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_attachments.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Unique username for display purposes. Can be changed later.', max_length=30, null=True, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('about', models.TextField(blank=True, help_text='Tell others about yourself (max 500 characters)', max_length=500, null=True, verbose_name='About Yourself')),
                ('current_status', models.CharField(blank=True, help_text="User's current status (e.g., Available, Busy, etc.)", max_length=100, null=True, verbose_name='Current Status')),
                ('note', models.TextField(blank=True, help_text='Personal notes or additional information', null=True, verbose_name='Personal Note')),
                ('is_guest_converted', models.BooleanField(default=False, help_text='True if this user was created from a guest checkout', verbose_name='Converted from Guest')),
                ('email_verified', models.BooleanField(default=False, help_text='True if user has verified their email address', verbose_name='Email Verified')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del contacto', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('nombre', models.CharField(help_text='Nombre completo del contacto', max_length=100, verbose_name='Nombre')),
                ('numero', models.CharField(blank=True, help_text='Número de teléfono del contacto (opcional)', max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('asunto', models.CharField(help_text='Asunto del mensaje', max_length=200, verbose_name='Asunto')),
                ('texto', models.TextField(help_text='Contenido del mensaje', verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, help_text='Si el mensaje ha sido leído por el administrador', verbose_name='Leído')),
                ('is_responded', models.BooleanField(default=False, help_text='Si el mensaje ha sido respondido', verbose_name='Respondido')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas del administrador', null=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='crushme_app_created_ca2316_idx'), models.Index(fields=['is_read'], name='crushme_app_is_read_f5c22a_idx'), models.Index(fields=['is_responded'], name='crushme_app_is_resp_b9274c_idx'), models.Index(fields=['email'], name='crushme_app_email_ec3288_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Number of orders placed as guest', verbose_name='Total Orders')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent as guest', max_digits=10, verbose_name='Total Spent')),
                ('has_been_converted', models.BooleanField(default=False, help_text='True if guest has registered as full user', verbose_name='Converted to User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL, verbose_name='Converted User Account')),
            ],
            options={
                'verbose_name': 'Guest User',
                'verbose_name_plural': 'Guest Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order identifier', max_length=32, unique=True, verbose_name='Order Number')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Order Status')),
                ('email', models.EmailField(help_text='Customer email address', max_length=254, verbose_name='Email')),
                ('name', models.CharField(help_text='Customer full name', max_length=200, verbose_name='Full Name')),
                ('country', models.CharField(help_text='Shipping country', max_length=100, verbose_name='Country')),
                ('state', models.CharField(help_text='Shipping state or province', max_length=100, verbose_name='State/Province')),
                ('city', models.CharField(help_text='Shipping city', max_length=100, verbose_name='City')),
                ('zipcode', models.CharField(help_text='Postal/Zip code', max_length=20, verbose_name='Zip Code')),
                ('address_line_1', models.CharField(help_text='Primary address line', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, help_text='Secondary address line (optional)', max_length=255, verbose_name='Address Line 2')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, verbose_name='Phone Number')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions', verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.IntegerField(help_text='ID of the product in WooCommerce', verbose_name='WooCommerce Product ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of purchase', max_digits=10, verbose_name='Unit Price')),
                ('product_name', models.CharField(help_text='Product name at the time of purchase', max_length=200, verbose_name='Product Name (at purchase)')),
                ('product_description', models.TextField(blank=True, help_text='Product description at the time of purchase', verbose_name='Product Description (at purchase)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crushme_app.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 4 digits', regex='^\\d{4}$')])),
                ('code_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], default='password_reset', max_length=20, verbose_name='Code Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Code',
                'verbose_name_plural': 'Verification Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product', max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(help_text='Detailed description of the product', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in USD', max_digits=10, verbose_name='Price')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('home_garden', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('beauty', 'Beauty & Personal Care'), ('automotive', 'Automotive'), ('food', 'Food & Beverages'), ('health', 'Health & Wellness'), ('jewelry', 'Jewelry & Accessories'), ('music', 'Music & Instruments'), ('art', 'Art & Crafts'), ('office', 'Office Supplies'), ('pet', 'Pet Supplies'), ('other', 'Other')], default='other', help_text='Product category', max_length=50, verbose_name='Category')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available quantity in stock', verbose_name='Stock Quantity')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is available for purchase', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gallery', django_attachments.fields.GalleryField(help_text='Image gallery for the product', on_delete=django.db.models.deletion.CASCADE, related_name='products_with_attachment', to='django_attachments.library', verbose_name='Product Gallery')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of adding to cart', max_digits=10, verbose_name='Unit Price')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crushme_app.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='crushme_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.IntegerField(db_index=True, help_text='ID del producto en WooCommerce', verbose_name='WooCommerce Product ID')),
                ('anonymous_name', models.CharField(blank=True, help_text='Nombre del usuario anónimo', max_length=100, null=True, verbose_name='Nombre Anónimo')),
                ('anonymous_email', models.EmailField(blank=True, help_text='Email del usuario anónimo', max_length=254, null=True, verbose_name='Email Anónimo')),
                ('rating', models.IntegerField(help_text='Calificación del producto (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('title', models.CharField(blank=True, help_text='Título de la reseña', max_length=200, verbose_name='Título')),
                ('comment', models.TextField(help_text='Comentario detallado de la reseña', verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, help_text='Si la reseña está aprobada y visible', verbose_name='Activa')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Si es una reseña de una compra verificada', verbose_name='Compra Verificada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que hizo la reseña (opcional para anónimos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP/Postal Code')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('additional_details', models.TextField(blank=True, help_text='Additional address details or delivery instructions', null=True, verbose_name='Additional Details')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='Default Shipping Address')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='Default Billing Address')),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest checkouts', max_length=254, null=True, verbose_name='Guest Email')),
                ('guest_first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guest First Name')),
                ('guest_last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guest Last Name')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guest Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this address. Null for guest checkouts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_gallery/%Y/%m/%d/', verbose_name='Gallery Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image Caption')),
                ('is_profile_picture', models.BooleanField(default=False, help_text='Set as profile picture', verbose_name='Profile Picture')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gallery Photo',
                'verbose_name_plural': 'User Gallery Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the link', max_length=100, verbose_name='Link Title')),
                ('url', models.URLField(help_text='The actual link URL', verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which links are displayed', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is visible', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Link',
                'verbose_name_plural': 'User Links',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the wishlist', max_length=200, verbose_name='Wishlist Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the wishlist', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the wishlist is active', verbose_name='Is Active')),
                ('unique_link', models.UUIDField(default=uuid.uuid4, help_text='UUID for public sharing of the wishlist', unique=True, verbose_name='Unique Link')),
                ('shipping_data', models.JSONField(blank=True, default=dict, help_text='JSON data containing shipping information (name, address, phone, email)', verbose_name='Shipping Data')),
                ('is_public', models.BooleanField(default=False, help_text='Whether the wishlist can be viewed by others via link', verbose_name='Is Public')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wish List',
                'verbose_name_plural': 'Wish Lists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_wishlists', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='crushme_app.wishlist', verbose_name='Wishlist')),
            ],
            options={
                'verbose_name': 'Favorite Wishlist',
                'verbose_name_plural': 'Favorite Wishlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.IntegerField(blank=True, default=None, help_text='ID del producto en WooCommerce', null=True, verbose_name='WooCommerce Product ID')),
                ('product_data', models.JSONField(blank=True, default=dict, help_text='Cached product information from WooCommerce', verbose_name='Product Data Cache')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this item', verbose_name='Notes')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.ForeignKey(blank=True, help_text='Legacy field for local products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='crushme_app.product', verbose_name='Product (Legacy)')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crushme_app.wishlist', verbose_name='Wishlist')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.IntegerField(db_index=True, help_text='ID del producto en WooCommerce', verbose_name='WooCommerce Product ID')),
                ('product_data', models.JSONField(blank=True, default=dict, help_text='Cached product information from WooCommerce (name, price, image, etc.)', verbose_name='Product Data Cache')),
                ('cache_updated_at', models.DateTimeField(blank=True, help_text='Last time product data was fetched from WooCommerce', null=True, verbose_name='Cache Updated At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite Product',
                'verbose_name_plural': 'Favorite Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='crushme_app_user_id_213247_idx'), models.Index(fields=['woocommerce_product_id'], name='crushme_app_woocomm_76ac66_idx')],
                'unique_together': {('user', 'woocommerce_product_id')},
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Contenido del post (máximo 1000 caracteres)', max_length=1000, verbose_name='Texto')),
                ('color', models.CharField(default='#000000', help_text='Código hexadecimal del color (ej: #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un código hexadecimal válido (ej: #FF5733)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Feed Post',
                'verbose_name_plural': 'Feed Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='crushme_app_created_719500_idx'), models.Index(fields=['user', '-created_at'], name='crushme_app_user_id_326d16_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='crushme_app_user_id_9c6769_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='crushme_app_status_5f4bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='crushme_app_order_n_94a0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'woocommerce_product_id'], name='crushme_app_order_i_eb5bc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'woocommerce_product_id')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='crushme_app_categor_5f076d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='crushme_app_is_acti_a04fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='crushme_app_created_cadc12_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='crushme_app_cart_id_3c131c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['woocommerce_product_id', '-created_at'], name='crushme_app_woocomm_cd3ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_active'], name='crushme_app_is_acti_3b6409_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='crushme_app_rating_c1ffe3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='crushme_app_user_id_4e421a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'woocommerce_product_id')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', '-created_at'], name='crushme_app_user_id_2f7f12_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['unique_link'], name='crushme_app_unique__4ecd04_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_public'], name='crushme_app_is_publ_a6a02c_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritewishlist',
            index=models.Index(fields=['user', '-created_at'], name='crushme_app_user_id_6f43cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritewishlist',
            unique_together={('user', 'wishlist')},
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'woocommerce_product_id'], name='crushme_app_wishlis_645b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['woocommerce_product_id'], name='crushme_app_woocomm_8c7f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['priority'], name='crushme_app_priorit_518097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'woocommerce_product_id')},
        ),
    ]
