# Generated by Django 5.1.5 on 2025-09-29 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text='Tell others about yourself (max 500 characters)', max_length=500, null=True, verbose_name='About Yourself'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest_converted',
            field=models.BooleanField(default=False, help_text='True if this user was created from a guest checkout', verbose_name='Converted from Guest'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Unique username for display purposes. Can be changed later.', max_length=30, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('total_orders', models.PositiveIntegerField(default=0, help_text='Number of orders placed as guest', verbose_name='Total Orders')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent as guest', max_digits=10, verbose_name='Total Spent')),
                ('has_been_converted', models.BooleanField(default=False, help_text='True if guest has registered as full user', verbose_name='Converted to User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL, verbose_name='Converted User Account')),
            ],
            options={
                'verbose_name': 'Guest User',
                'verbose_name_plural': 'Guest Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP/Postal Code')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='Default Shipping Address')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='Default Billing Address')),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest checkouts', max_length=254, null=True, verbose_name='Guest Email')),
                ('guest_first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guest First Name')),
                ('guest_last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Guest Last Name')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guest Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this address. Null for guest checkouts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_gallery/%Y/%m/%d/', verbose_name='Gallery Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image Caption')),
                ('is_profile_picture', models.BooleanField(default=False, help_text='Set as profile picture', verbose_name='Profile Picture')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gallery Photo',
                'verbose_name_plural': 'User Gallery Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the link', max_length=100, verbose_name='Link Title')),
                ('url', models.URLField(help_text='The actual link URL', verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which links are displayed', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is visible', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Link',
                'verbose_name_plural': 'User Links',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
