# Generated by Django 5.1.5 on 2025-10-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='crushme_app_cart_id_3c131c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.URLField(blank=True, help_text='Main image URL from WooCommerce', max_length=1000, null=True, verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(default='Unknown Product', help_text='Name of the product from WooCommerce', max_length=500, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='woocommerce_product_id',
            field=models.IntegerField(default=0, help_text='ID of the product in WooCommerce', verbose_name='WooCommerce Product ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Legacy field for local products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='crushme_app.product', verbose_name='Product (Legacy)'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'woocommerce_product_id')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'woocommerce_product_id'], name='crushme_app_cart_id_0110be_idx'),
        ),
    ]
