# Generated by Django 5.1.5 on 2025-09-29 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0002_user_about_user_is_guest_converted_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification Code', 'verbose_name_plural': 'Verification Codes'},
        ),
        migrations.AddField(
            model_name='passwordcode',
            name='code_type',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], default='password_reset', max_length=20, verbose_name='Code Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True if user has verified their email address', verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='passwordcode',
            name='code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 4 digits', regex='^\\d{4}$')]),
        ),
    ]
