# Generated by Django 5.1.5 on 2025-10-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0002_remove_cartitem_crushme_app_cart_id_3c131c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/%Y/%m/%d/', verbose_name='Profile Picture'),
        ),
    ]
