# Generated by Django 5.1.5 on 2025-09-29 21:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0003_alter_passwordcode_options_passwordcode_code_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=True, help_text='Si la sincronización automática con WooCommerce está habilitada', verbose_name='Auto-sincronización Habilitada')),
                ('sync_interval_hours', models.PositiveIntegerField(default=6, help_text='Cada cuántas horas sincronizar con WooCommerce', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Intervalo de Sincronización (horas)')),
                ('default_products_per_carousel', models.PositiveIntegerField(default=12, help_text='Número por defecto de productos por carrusel', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Productos por Carrusel (por defecto)')),
                ('show_out_of_stock', models.BooleanField(default=False, help_text='Si mostrar productos sin stock en los carruseles', verbose_name='Mostrar Productos Agotados')),
                ('cache_duration_minutes', models.PositiveIntegerField(default=30, help_text='Cuánto tiempo mantener los datos en caché', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Duración de Caché (minutos)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de Carruseles',
                'verbose_name_plural': 'Configuraciones de Carruseles',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar el carrusel', max_length=200, verbose_name='Nombre del Carrusel')),
                ('carousel_type', models.CharField(choices=[('home_featured', 'Productos Destacados - Inicio'), ('home_new', 'Productos Nuevos - Inicio'), ('category_featured', 'Productos Destacados - Categoría'), ('sale_products', 'Productos en Oferta'), ('recommended', 'Productos Recomendados'), ('trending', 'Productos Tendencia')], help_text='Tipo de carrusel donde se mostrará', max_length=50, verbose_name='Tipo de Carrusel')),
                ('is_active', models.BooleanField(default=True, help_text='Si el carrusel está activo y se muestra en el frontend', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = mayor prioridad)', verbose_name='Orden')),
                ('max_products', models.PositiveIntegerField(default=12, help_text='Número máximo de productos a mostrar en este carrusel', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Máximo de Productos')),
                ('auto_populate', models.BooleanField(default=False, help_text='Si debe llenarse automáticamente con productos de WooCommerce', verbose_name='Auto-poblar')),
                ('auto_populate_criteria', models.JSONField(blank=True, default=dict, help_text='Criterios JSON para auto-poblar (categorías, precios, etc.)', verbose_name='Criterios de Auto-población')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Carrusel de Productos',
                'verbose_name_plural': 'Carruseles de Productos',
                'ordering': ['carousel_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.PositiveIntegerField(help_text='ID del producto en WooCommerce', verbose_name='ID Producto WooCommerce')),
                ('product_name', models.CharField(blank=True, help_text='Nombre del producto (actualizado automáticamente)', max_length=300, verbose_name='Nombre del Producto')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del producto (actualizado automáticamente)', max_digits=10, null=True, verbose_name='Precio')),
                ('product_image_url', models.URLField(blank=True, help_text='URL de la imagen principal (actualizada automáticamente)', verbose_name='URL de Imagen')),
                ('product_stock_status', models.CharField(blank=True, help_text='Estado del stock (actualizado automáticamente)', max_length=50, verbose_name='Estado de Stock')),
                ('product_categories', models.JSONField(blank=True, default=list, help_text='Categorías del producto (actualizadas automáticamente)', verbose_name='Categorías')),
                ('custom_title', models.CharField(blank=True, help_text='Título personalizado (opcional, sobrescribe el nombre del producto)', max_length=300, verbose_name='Título Personalizado')),
                ('custom_description', models.TextField(blank=True, help_text='Descripción personalizada para mostrar en el carrusel', verbose_name='Descripción Personalizada')),
                ('custom_image_url', models.URLField(blank=True, help_text='URL de imagen personalizada (opcional, sobrescribe la imagen del producto)', verbose_name='Imagen Personalizada')),
                ('is_active', models.BooleanField(default=True, help_text='Si este producto se muestra en el carrusel', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro del carrusel (menor número = mayor prioridad)', verbose_name='Orden')),
                ('show_badge', models.CharField(blank=True, choices=[('new', 'Nuevo'), ('sale', 'Oferta'), ('featured', 'Destacado'), ('trending', 'Tendencia'), ('bestseller', 'Más Vendido')], help_text='Etiqueta especial a mostrar en el producto', max_length=50, verbose_name='Etiqueta')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última vez que se sincronizó con WooCommerce', null=True, verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='crushme_app.featuredproductcarousel', verbose_name='Carrusel')),
            ],
            options={
                'verbose_name': 'Producto Destacado',
                'verbose_name_plural': 'Productos Destacados',
                'ordering': ['carousel', 'order', 'product_name'],
                'unique_together': {('carousel', 'woocommerce_product_id')},
            },
        ),
    ]
