# Generated by Django 5.1.5 on 2025-10-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="User's cover/banner image for profile", null=True, upload_to='cover_images/%Y/%m/%d/', verbose_name='Cover Image'),
        ),
    ]
