# Generated by Django 5.1.5 on 2025-10-01 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0004_carouselsettings_featuredproductcarousel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woocommerce_product_id', models.PositiveIntegerField(db_index=True, help_text='ID del producto en WooCommerce', verbose_name='WooCommerce Product ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('title', models.CharField(help_text='Título de la reseña', max_length=200, verbose_name='Título')),
                ('comment', models.TextField(help_text='Comentario detallado sobre el producto', verbose_name='Comentario')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Si la reseña es de una compra verificada', verbose_name='Compra verificada')),
                ('is_approved', models.BooleanField(default=True, help_text='Si la reseña está aprobada para mostrar', verbose_name='Aprobada')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Número de personas que marcaron la reseña como útil', verbose_name='Votos útiles')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(help_text='Usuario que escribió la reseña', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de voto')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='crushme_app.review', verbose_name='Reseña')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto útil',
                'verbose_name_plural': 'Votos útiles',
            },
        ),
        migrations.DeleteModel(
            name='CarouselSettings',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
        migrations.DeleteModel(
            name='FeaturedProductCarousel',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['woocommerce_product_id'], name='crushme_app_woocomm_405c46_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='crushme_app_rating_c1ffe3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='crushme_app_is_appr_c94379_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='crushme_app_created_04bc16_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['woocommerce_product_id', 'is_approved'], name='crushme_app_woocomm_3bbdd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('woocommerce_product_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
    ]
