# Generated by Django 5.1.5 on 2025-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0004_user_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crush_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for Crush verification rejection', null=True, verbose_name='Crush Rejection Reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='crush_requested_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when Crush verification was requested', null=True, verbose_name='Crush Requested At'),
        ),
        migrations.AddField(
            model_name='user',
            name='crush_verification_status',
            field=models.CharField(choices=[('none', 'No Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Status of Crush verification request', max_length=20, verbose_name='Crush Verification Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='crush_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when Crush was verified/approved', null=True, verbose_name='Crush Verified At'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_crush',
            field=models.BooleanField(default=False, help_text='True if user is a verified Crush/Webcammer', verbose_name='Is Crush (Verified)'),
        ),
    ]
