# Generated by Django 5.1.5 on 2025-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0005_user_crush_rejection_reason_user_crush_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='woocommerce_variation_id',
            field=models.IntegerField(blank=True, help_text='ID of the product variation in WooCommerce (optional)', null=True, verbose_name='WooCommerce Variation ID'),
        ),
    ]
