# Generated by Django 5.1.5 on 2025-10-01 19:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0005_create_review_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewhelpful',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewhelpful',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='crushme_app_woocomm_405c46_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='crushme_app_is_appr_c94379_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='crushme_app_created_04bc16_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='crushme_app_woocomm_3bbdd7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'woocommerce_product_id')},
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous_email',
            field=models.EmailField(blank=True, help_text='Email del usuario anónimo', max_length=254, null=True, verbose_name='Email Anónimo'),
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous_name',
            field=models.CharField(blank=True, help_text='Nombre del usuario anónimo', max_length=100, null=True, verbose_name='Nombre Anónimo'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si la reseña está aprobada y visible', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Comentario detallado de la reseña', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Si es una reseña de una compra verificada', verbose_name='Compra Verificada'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Calificación del producto (1-5 estrellas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, help_text='Título de la reseña', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que hizo la reseña (opcional para anónimos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='woocommerce_product_id',
            field=models.IntegerField(db_index=True, help_text='ID del producto en WooCommerce', verbose_name='WooCommerce Product ID'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['woocommerce_product_id', '-created_at'], name='crushme_app_woocomm_cd3ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_active'], name='crushme_app_is_acti_3b6409_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='crushme_app_user_id_4e421a_idx'),
        ),
        migrations.DeleteModel(
            name='ReviewHelpful',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
    ]
