# Generated by Django 5.1.5 on 2025-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0006_orderitem_woocommerce_variation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.TextField(blank=True, help_text='Personalized message for gifts and presents', verbose_name='Gift Message'),
        ),
    ]
