# Generated by Django 5.1.5 on 2025-10-01 22:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0006_alter_reviewhelpful_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del contacto', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('nombre', models.CharField(help_text='Nombre completo del contacto', max_length=100, verbose_name='Nombre')),
                ('numero', models.CharField(blank=True, help_text='Número de teléfono del contacto (opcional)', max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('asunto', models.CharField(help_text='Asunto del mensaje', max_length=200, verbose_name='Asunto')),
                ('texto', models.TextField(help_text='Contenido del mensaje', verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, help_text='Si el mensaje ha sido leído por el administrador', verbose_name='Leído')),
                ('is_responded', models.BooleanField(default=False, help_text='Si el mensaje ha sido respondido', verbose_name='Respondido')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas del administrador', null=True, verbose_name='Notas del Administrador')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='crushme_app_created_ca2316_idx'), models.Index(fields=['is_read'], name='crushme_app_is_read_f5c22a_idx'), models.Index(fields=['is_responded'], name='crushme_app_is_resp_b9274c_idx'), models.Index(fields=['email'], name='crushme_app_email_ec3288_idx')],
            },
        ),
    ]
