# Generated by Django 5.1.5 on 2025-10-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0007_order_gift_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='True if this order was sent as a gift to another user', verbose_name='Is Gift Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_username',
            field=models.CharField(blank=True, help_text='Username of the person who received this gift', max_length=150, null=True, verbose_name='Gift Receiver Username'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_username',
            field=models.CharField(blank=True, help_text='Username of the person who sent this gift (if different from order owner)', max_length=150, null=True, verbose_name='Gift Sender Username'),
        ),
    ]
