# Generated by Django 5.1.5 on 2025-10-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0008_order_is_gift_order_receiver_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='woocommerce_order_id',
            field=models.IntegerField(blank=True, help_text='ID of the corresponding order in WooCommerce (populated after sync)', null=True, verbose_name='WooCommerce Order ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='purchase_history',
            field=models.ManyToManyField(blank=True, help_text='Orders made by this user', related_name='purchasers', to='crushme_app.order', verbose_name='Purchase History'),
        ),
        migrations.AddField(
            model_name='user',
            name='received_gifts',
            field=models.ManyToManyField(blank=True, help_text='Gift orders received by this user', related_name='gift_recipients', to='crushme_app.order', verbose_name='Received Gifts'),
        ),
        migrations.AddField(
            model_name='user',
            name='sent_gifts_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of gifts sent by this user', verbose_name='Sent Gifts Count'),
        ),
    ]
