# Generated by Django 5.1.5 on 2025-10-20 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0010_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('categories', 'Categories Only'), ('products', 'Products Only'), ('variations', 'Variations Only')], max_length=20, verbose_name='Sync Type')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='started', max_length=20, verbose_name='Status')),
                ('categories_synced', models.IntegerField(default=0, verbose_name='Categories Synced')),
                ('products_synced', models.IntegerField(default=0, verbose_name='Products Synced')),
                ('variations_synced', models.IntegerField(default=0, verbose_name='Variations Synced')),
                ('images_synced', models.IntegerField(default=0, verbose_name='Images Synced')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Errors Count')),
                ('error_details', models.TextField(blank=True, default='', verbose_name='Error Details')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
            ],
            options={
                'verbose_name': 'Product Sync Log',
                'verbose_name_plural': 'Product Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='crushme_app_started_004606_idx'), models.Index(fields=['status'], name='crushme_app_status_a0c7fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='WooCommerceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(db_index=True, unique=True, verbose_name='WooCommerce ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('wc_parent_id', models.IntegerField(db_index=True, default=0, verbose_name='WooCommerce Parent ID')),
                ('product_count', models.IntegerField(default=0, verbose_name='Product Count')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Image URL')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crushme_app.woocommercecategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'WooCommerce Category',
                'verbose_name_plural': 'WooCommerce Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WooCommerceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(db_index=True, unique=True, verbose_name='WooCommerce ID')),
                ('name', models.CharField(max_length=500, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('permalink', models.URLField(max_length=500, verbose_name='WooCommerce Link')),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped'), ('external', 'External'), ('variable', 'Variable')], db_index=True, default='simple', max_length=20, verbose_name='Product Type')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Short Description')),
                ('description', models.TextField(blank=True, default='', verbose_name='Full Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Price')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Regular Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price')),
                ('on_sale', models.BooleanField(default=False, verbose_name='On Sale')),
                ('stock_status', models.CharField(default='instock', max_length=20, verbose_name='Stock Status')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='Stock Quantity')),
                ('manage_stock', models.BooleanField(default=False, verbose_name='Manage Stock')),
                ('attributes', models.JSONField(blank=True, default=list, verbose_name='Attributes')),
                ('default_attributes', models.JSONField(blank=True, default=list, verbose_name='Default Attributes')),
                ('weight', models.CharField(blank=True, default='', max_length=50, verbose_name='Weight')),
                ('length', models.CharField(blank=True, default='', max_length=50, verbose_name='Length')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='Width')),
                ('height', models.CharField(blank=True, default='', max_length=50, verbose_name='Height')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Rating Count')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total Sales')),
                ('status', models.CharField(db_index=True, default='publish', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('parent_id', models.IntegerField(default=0, verbose_name='Parent Product ID')),
                ('date_created_wc', models.DateTimeField(blank=True, null=True, verbose_name='WC Created Date')),
                ('date_modified_wc', models.DateTimeField(blank=True, null=True, verbose_name='WC Modified Date')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='crushme_app.woocommercecategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'WooCommerce Product',
                'verbose_name_plural': 'WooCommerce Products',
                'ordering': ['-date_created_wc'],
            },
        ),
        migrations.CreateModel(
            name='WooCommerceProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(verbose_name='WooCommerce Image ID')),
                ('src', models.URLField(max_length=500, verbose_name='Full Size URL')),
                ('thumbnail', models.URLField(blank=True, default='', max_length=500, verbose_name='Thumbnail URL')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Image Name')),
                ('alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt Text')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crushme_app.woocommerceproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['position', 'wc_id'],
            },
        ),
        migrations.CreateModel(
            name='WooCommerceProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(db_index=True, unique=True, verbose_name='WooCommerce Variation ID')),
                ('wc_product_id', models.IntegerField(db_index=True, verbose_name='WooCommerce Product ID')),
                ('permalink', models.URLField(max_length=500, verbose_name='WooCommerce Link')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Price')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Regular Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price')),
                ('on_sale', models.BooleanField(default=False, verbose_name='On Sale')),
                ('stock_status', models.CharField(default='instock', max_length=20, verbose_name='Stock Status')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='Stock Quantity')),
                ('manage_stock', models.BooleanField(default=False, verbose_name='Manage Stock')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Variation Attributes')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Image URL')),
                ('weight', models.CharField(blank=True, default='', max_length=50, verbose_name='Weight')),
                ('length', models.CharField(blank=True, default='', max_length=50, verbose_name='Length')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='Width')),
                ('height', models.CharField(blank=True, default='', max_length=50, verbose_name='Height')),
                ('status', models.CharField(default='publish', max_length=20, verbose_name='Status')),
                ('date_created_wc', models.DateTimeField(blank=True, null=True, verbose_name='WC Created Date')),
                ('date_modified_wc', models.DateTimeField(blank=True, null=True, verbose_name='WC Modified Date')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='crushme_app.woocommerceproduct', verbose_name='Parent Product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'ordering': ['wc_id'],
            },
        ),
        migrations.AddIndex(
            model_name='woocommercecategory',
            index=models.Index(fields=['wc_id'], name='crushme_app_wc_id_07fa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommercecategory',
            index=models.Index(fields=['slug'], name='crushme_app_slug_11bbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommercecategory',
            index=models.Index(fields=['wc_parent_id'], name='crushme_app_wc_pare_a55f90_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproduct',
            index=models.Index(fields=['wc_id'], name='crushme_app_wc_id_b8565c_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproduct',
            index=models.Index(fields=['slug'], name='crushme_app_slug_43517d_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproduct',
            index=models.Index(fields=['product_type'], name='crushme_app_product_257bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproduct',
            index=models.Index(fields=['status'], name='crushme_app_status_eaa366_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproduct',
            index=models.Index(fields=['featured'], name='crushme_app_feature_d45c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproduct',
            index=models.Index(fields=['on_sale'], name='crushme_app_on_sale_1adf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproductimage',
            index=models.Index(fields=['product', 'position'], name='crushme_app_product_4fd94c_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproductvariation',
            index=models.Index(fields=['wc_id'], name='crushme_app_wc_id_492098_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproductvariation',
            index=models.Index(fields=['wc_product_id'], name='crushme_app_wc_prod_623d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceproductvariation',
            index=models.Index(fields=['product'], name='crushme_app_product_db6145_idx'),
        ),
    ]
