# Generated by Django 5.1.5 on 2025-10-20 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0011_productsynclog_woocommercecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPriceMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje de margen por defecto', max_digits=5, verbose_name='Default Margin Percentage')),
                ('use_fixed_multiplier', models.BooleanField(default=False, verbose_name='Use Fixed Multiplier')),
                ('fixed_multiplier', models.DecimalField(decimal_places=2, default=1.2, max_digits=5, verbose_name='Fixed Multiplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Default Price Margin',
                'verbose_name_plural': 'Default Price Margins',
            },
        ),
        migrations.CreateModel(
            name='CategoryPriceMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de margen (ej: 30.00 para 30%)', max_digits=5, verbose_name='Margin Percentage')),
                ('use_fixed_multiplier', models.BooleanField(default=False, help_text='Usar multiplicador fijo en lugar de margen porcentual', verbose_name='Use Fixed Multiplier')),
                ('fixed_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador fijo (ej: 1.30 para +30%)', max_digits=5, verbose_name='Fixed Multiplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_margin', to='crushme_app.woocommercecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Price Margin',
                'verbose_name_plural': 'Category Price Margins',
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='TranslatedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('product_name', 'Product Name'), ('product_short_desc', 'Product Short Description'), ('product_desc', 'Product Description'), ('category_name', 'Category Name'), ('category_desc', 'Category Description'), ('variation_attribute', 'Variation Attribute')], db_index=True, max_length=30, verbose_name='Content Type')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='WooCommerce ID')),
                ('source_language', models.CharField(default='es', max_length=5, verbose_name='Source Language')),
                ('target_language', models.CharField(db_index=True, max_length=5, verbose_name='Target Language')),
                ('source_text', models.TextField(verbose_name='Original Text')),
                ('translated_text', models.TextField(verbose_name='Translated Text')),
                ('translation_engine', models.CharField(default='argostranslate', max_length=50, verbose_name='Translation Engine')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Manually Verified')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Translated Content',
                'verbose_name_plural': 'Translated Contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'target_language'], name='crushme_app_content_d869d4_idx'), models.Index(fields=['object_id', 'content_type'], name='crushme_app_object__02a80c_idx'), models.Index(fields=['target_language'], name='crushme_app_target__14532b_idx')],
                'unique_together': {('content_type', 'object_id', 'target_language')},
            },
        ),
    ]
