# Generated by Django 5.1.5 on 2025-10-23 20:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0012_defaultpricemargin_categorypricemargin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique discount code (e.g., SUMMER2024, WELCOME10)', max_length=50, unique=True, verbose_name='Discount Code')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this discount code is currently active', verbose_name='Is Active')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used', verbose_name='Times Used')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this code can be used (leave empty for unlimited)', null=True, verbose_name='Max Uses')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='crushme_app_code_23baca_idx'), models.Index(fields=['is_active'], name='crushme_app_is_acti_64fadf_idx')],
            },
        ),
    ]
