# Generated by Django 5.1.5 on 2025-10-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0013_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='style',
            field=models.CharField(choices=[('timeline-pink-dream', 'Pink Dream'), ('timeline-purple-passion', 'Purple Passion'), ('timeline-rose-blush', 'Rose Blush'), ('timeline-ocean-blue', 'Ocean Blue'), ('timeline-coral-sunset', 'Coral Sunset'), ('timeline-midnight-rose', 'Midnight Rose')], default='timeline-pink-dream', help_text='Tema visual del post en el timeline', max_length=50, verbose_name='Estilo'),
        ),
    ]
