# Generated by Django 5.1.5 on 2025-10-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0014_add_style_to_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='color',
        ),
        migrations.AddField(
            model_name='feed',
            name='action',
            field=models.CharField(choices=[('signup', 'User Signup'), ('password_reset', 'Password Reset'), ('order_confirmation', 'Order Confirmation'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('general', 'General Post')], default='general', help_text='Tipo de acción que generó este post', max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='style',
            field=models.CharField(choices=[('timeline-pink-dream', 'Pink Dream'), ('timeline-purple-passion', 'Purple Passion'), ('timeline-rose-blush', 'Rose Blush'), ('timeline-ocean-blue', 'Ocean Blue'), ('timeline-coral-sunset', 'Coral Sunset'), ('timeline-midnight-rose', 'Midnight Rose')], default='timeline-midnight-rose', help_text='Tema visual del post en el timeline', max_length=50, verbose_name='Estilo'),
        ),
    ]
