# Generated by Django 5.1.5 on 2025-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0016_change_username_field_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='shipping_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data containing shipping information (name, address, phone, email)', null=True, verbose_name='Shipping Data'),
        ),
    ]
