# Generated by Django 5.1.5 on 2025-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0017_fix_wishlist_shipping_data_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, help_text='Payment provider used for this order (paypal, wompi, etc.)', max_length=50, null=True, verbose_name='Payment Provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID from payment provider (PayPal, Wompi, etc.)', max_length=255, null=True, unique=True, verbose_name='Transaction ID'),
        ),
    ]
