# Generated by Django 5.2.17 on 2026-08-20 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0018_order_payment_provider_order_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('wompi', 'Wompi')], max_length=20)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('order_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('processed', 'Processed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_session', to='crushme_app.order')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='crushme_app_provide_e3c9f5_idx'), models.Index(fields=['created_at'], name='crushme_app_created_f7504d_idx')],
            },
        ),
    ]
