# Generated by Django 5.2.17 on 2026-08-20 02:03

import crushme_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushme_app', '0019_paymentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, help_text="User's cover/banner image for profile", null=True, upload_to='cover_images/%Y/%m/%d/', validators=[crushme_app.validators.validate_image_upload], verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/%Y/%m/%d/', validators=[crushme_app.validators.validate_image_upload], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='image',
            field=models.ImageField(upload_to='user_gallery/%Y/%m/%d/', validators=[crushme_app.validators.validate_image_upload], verbose_name='Gallery Image'),
        ),
    ]
